name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

  # steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Build
  #     run: npm run build

  #   - name: Deploy
  #     run: npm run ng deploy


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm install
          npm run ng deploy
